# Generated by Django 5.1.4 on 2024-12-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='primer_apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='last_name',
            new_name='segundo_apellido',
        ),
    ]
